geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = "admin"

urlpatterns = [
    path("users/", adminapp.UserListView.as_view(), name="users"),
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path("users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", adminapp.delete_user, name="delete_user"),

    path("categories/", adminapp.CategoryListView.as_view(), name="categories"),
    path("category/create/", adminapp.create_category, name="create_category"),
    path("category/update/<int:pk>/", adminapp.update_category, name="update_category"),
    path("category/delete/<int:pk>/", adminapp.delete_category, name="delete_category"),

    path("products/<int:category_pk>/", adminapp.products, name="products"),
    path("product/<int:category_pk>/create/", adminapp.create_product, name="create_product"),
    path("product/update/<int:product_pk>/", adminapp.update_product, name="update_product"),
    path("product/delete/<int:product_pk>/", adminapp.delete_product, name="delete_product"),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.view, name="view"),
    path("add/<int:product_id>/", basketapp.add, name="add"),
    path("remove/<int:basket_id>/", basketapp.remove, name="remove"),
    path("edit/<int:basket_id>/<int:quantity>/", basketapp.edit, name="edit"),

]

geekshop/geekshop/urls.py
from mainapp import views as mainapp
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.main, name="index"),
    path("products/", mainapp.products, name="products"),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("category/<int:pk>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geekshop/mainapp/models.py
from distutils.command.upload import upload
from email.mime import image
from unicodedata import name
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.CharField(max_length=140)
    is_active = models.BooleanField(default=True)


def __str__(self):
    return f'{self.id}: {self.name}'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=25)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product_images', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quatity = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)


def __str__(self):
    return f'{self.id}: {self.name}'

geekshop/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
import json
from .models import Product, Category


with open('data.txt') as json_file:
    product_list = json.load(json_file)

MENU_LINKS = {
    "index": "Главная",
    "products": "Продукты",
    "contact": "Контакты",
}


def main(request):
    return render(request, "mainapp/index.html", context={
        "title": "Главная",
        "menu": MENU_LINKS,
    })


def products(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)[:3]
    return render(request, "mainapp/products.html", context={
        "title": "Продукты",
        "menu": MENU_LINKS,
        "hot_product": hot_product,
        "products": products,
        "categories": categories,
    })

def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category).order_by('price')
    paginator = Paginator(products, per_page=3)
    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse('category', args=[category.id]))
    return render(
        request, 
        "mainapp/category.html", 
        context={
            "title": 'Продукты',
            "menu": MENU_LINKS,
            "products": paginator.page(page),
            "category": category,
            "categories": categories,
        }
    )
    


def contact(request):
    return render(request, "mainapp/contact.html", context={
        "title": "Контакты",
        "menu": MENU_LINKS,
    })

def product(request, pk):
    categories = Category.objects.all()
    product = get_object_or_404(Product, pk=pk)
    return render(request, "mainapp/product.html", context={
        "title": product.name,
        "menu": MENU_LINKS,
        "product": product,
        "category": product.category,
        "categories": categories,
    })

geekshop/mainapp/templates/mainapp/includes/categories_menu_inc.html
<ul class="links-menu">
    {% with url_name=request.resolver_match.url_name %}
    {% with category_id=request.resolver_match.kwargs.pk %}
    <li><a href="{% url 'products' %}" class="{% if url_name == 'products' %}active{% endif %}">все</a></li>
    {% for category in categories %}
    <li><a href="{% url 'category' category.id %}" class="{% if url_name == 'category' and category_id == category.id %}active{% endif %}">{{ category.name }}</a></li>
    {% endfor %}
    {% endwith %}
    {% endwith %}
</ul>

geekshop/mainapp/templates/mainapp/includes/main_menu_inc.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        {% with url_name=request.resolver_match.url_name %}
        {% for link, name in menu.items %}
        <li><a href="{% url link %}" class="{% if url_name == link %} active {% endif %}">{{ name }}</a></li>
        {% endfor %}
        {% endwith %}
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'auth:edit' %}">{{user.username}}</a></li>
            <li><a href="{% url 'basket:view' %}">Корзина ({{request.user.basket.all|length}})</a></li>
            {% if request.user.is_superuser %}
            <li><a href="{% url 'admin:users' %}">Админка</a></li>
            {% endif %}
            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'auth:login' %}">Войти</a></li>
            <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>
</div>

geekshop/mainapp/templates/mainapp/includes/product_list_inc.html
{% load static %}
{% for product in products %}
<div class = "block"> 
<a href="{% url 'product' product.id %}">
    {% if product.image %}
        <img class="product_image" src="{{ product.image.url }}" alt="">
    {% else %}
        <img class="product_image" src="{% static 'css/img/not_image.png' %}" alt="">
    {% endif %}
    <div class="text">
        <img src="{% static '/css/img/icon-hover.png' %}" alt="img">
        <h4>{{ product.name|title }}</h4>
        <p>{{ product.description|upper|truncatewords:10 }}</p>
    </div>
</a>
</div>
{% endfor %}