geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = "admin"

urlpatterns = [
    path("users/", adminapp.UserListView.as_view(), name="users"),
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path("users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", adminapp.delete_user, name="delete_user"),

    path("categories/", adminapp.CategoryListView.as_view(), name="categories"),
    path("category/create/", adminapp.create_category, name="create_category"),
    path("category/update/<int:pk>/", adminapp.update_category, name="update_category"),
    path("category/delete/<int:pk>/", adminapp.delete_category, name="delete_category"),

    path("products/<int:category_pk>/", adminapp.products, name="products"),
    path("product/<int:category_pk>/create/", adminapp.create_product, name="create_product"),
    path("product/update/<int:product_pk>/", adminapp.update_product, name="update_product"),
    path("product/delete/<int:product_pk>/", adminapp.delete_product, name="delete_product"),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from mainapp import views as mainapp
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.main, name="index"),
    path("products/", mainapp.products, name="products"),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("category/<int:pk>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from authapp.models import ShopUser
from mainapp.models import Category, Product
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms.widgets import HiddenInput

class LoginForm(AuthenticationForm):
    pass

class RegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'city', 'age')

class UserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'city', 'age')
    
class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        
class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget = HiddenInput()

geekshop/adminapp/views.py
from itertools import product
from multiprocessing import context
from pyexpat import model
from unicodedata import category
from adminapp.forms import RegisterForm, UserEditForm
from authapp.models import ShopUser
from adminapp.forms import CategoryEditForm, ProductEditForm
from mainapp.models import Category, Product
from adminapp.utils import check_is_superuser
from django.contrib.auth.decorators import user_passes_test
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator

class TitleMixin:
    title = None
    
    def  get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.title
        return context
    
class CheckSuperuserMixin:
    @method_decorator(check_is_superuser)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    
class UserListView(CheckSuperuserMixin, TitleMixin, ListView):
    template_name = "adminapp/users.html"
    title = "Пользователи"
    
    def get_queryset(self):
        return ShopUser.objects.order_by('date_joined') 
    
            

class UserUpdateView(TitleMixin, UpdateView):
    template_name = "adminapp/update_user.html"
    model = ShopUser
    form_class = UserEditForm
    success_url = reverse_lazy('admin:users')
    title = "Редактирование пользователя"
    
        

@check_is_superuser
def delete_user(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    user.is_active = False
    user.save()
    return HttpResponseRedirect(reverse('admin:users'))
    
class UserCreateView(TitleMixin, CreateView):
    template_name = "adminapp/create_user.html"
    model = ShopUser
    form_class = RegisterForm
    success_url = reverse_lazy('admin:users')
    title = "Создание пользователя"
    
    

@check_is_superuser
def create_category(request):
    form = CategoryEditForm()
    
    if request.method == 'POST':
        form = CategoryEditForm(data=request.POST)
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:categories'))
            
    return render(request, 'adminapp/create_category.html', context={
            'title': 'Создание категории',
            'form': form
        }
    )

class CategoryListView(TitleMixin, ListView):
    template_name = "adminapp/categories.html"
    model = Category
    title = "Категории"


@check_is_superuser
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    form = CategoryEditForm(instance=category)
    
    if request.method == 'POST':
        form = CategoryEditForm(
            instance=category, 
            data=request.POST, 
        )
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:categories'))
            
    return render(request, 'adminapp/update_category.html', context={
            'title': 'Редактирование категории',
            'category': category,
            'form': form
        },
    )



@check_is_superuser
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.is_active = False
    category.save()
    return HttpResponseRedirect(reverse('admin:categories'))


@check_is_superuser
def create_product(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    form = ProductEditForm(initial={'category': category})    
    if request.method == 'POST':
        form = ProductEditForm(data=request.POST, files=request.FILES)
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:products', args=[category_pk]))
            
    return render(request, 'adminapp/create_product.html', context={
            "title": f"Создание продукта категории {category.name}",
            "category": category,
            "form": form
        }
    )


@check_is_superuser
def products(request, category_pk):
    category= get_object_or_404(Category, pk=category_pk)
    return render(request, "adminapp/products.html", context={
        "title": f"Категория: {category.name}",
        "products": Product.objects.filter(category=category),
        "category": category
    })

@check_is_superuser
def update_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    form = ProductEditForm(instance=product, initial={'category': product.category})
    
    if request.method == 'POST':
        form = ProductEditForm(
            instance=product, 
            data=request.POST,
            files=request.FILES, 
        )
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))
            
    return render(request, 'adminapp/update_product.html', context={
            "title": "Редактирование продукта",
            "product": product,
            "form": form
        },
    )


@check_is_superuser
def delete_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    product.is_active = False
    product.save()
    return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}{{ title }}{% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/pure-min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/basket-styles.css' %}"/>
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="content">
        <a class="pure-button pure-button-secondary" href="{% url 'index' %}">> - На сайт</a>
        <a class="pure-button pure-button-secondary" href="{% url 'admin:users' %}">> - Пользователи</a>
        <a class="pure-button pure-button-secondary" href="{% url 'admin:categories' %}">> - Категории</a>

        <h2>
            {{ title }}
        </h2>
            {% block content %}{% endblock %}
      
    </div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'admin:create_category' %}" class="pure-button pure-button-primary">Создать категорию</a>
<div class="users_list">
    {% for category in object_list %}
        <div>
            <span>{{ category.name }}</span>
            <span>{{ category.description }}</span>
            <a href="{% url 'admin:products' category.pk %}" class="pure-button pure-button-primary">К товарам категории</a>
            <a href="{% url 'admin:update_category' category.pk %}" class="pure-button pure-button-primary">Редактировать</a>
            <a href="{% url 'admin:delete_category' category.pk %}" class="pure-button pure-button-primary">Удалить</a>
        </div>
    {% endfor %}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_category.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <form class="pure-form" action="{% url 'admin:create_category' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button pure-button-primary" type="submit" value="Создать категорию">
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_product.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:create_product' category.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button pure-button-primary" type="submit" value="Создать продукт">
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/create_user.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <form class="pure-form" action="{% url 'admin:create_user' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button pure-button-primary" type="submit" value="Создать пользователя">
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'admin:create_product' category.pk %}" class="pure-button pure-button-primary">Создать продукт</a>
<div>
    {% for product in products %}
        <div>
            <span>{{ product.name }}</span>
            <span>{{ product.description }}</span>
            <span>{{ product.quantity }}</span>
            <a href="{% url 'admin:update_product' product.pk %}" class="pure-button pure-button-primary">Редактировать</a>
            <a href="{% url 'admin:delete_product' product.pk %}" class="pure-button pure-button-primary">Удалить</a>
        </div>
    {% endfor %}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_category.html
{% extends 'adminapp/base.html' %}
{% block content %}
<form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:update_category' category.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_product.html
{% extends 'adminapp/base.html' %}
{% block content %}
<form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:update_product' product.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/update_user.html
{% extends 'adminapp/base.html' %}
{% block content %}
{% if user.image %}
     <img src="{{ user.image.url }}"
{% endif %}

    <form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:update_user' object.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/upgrade_user.html
{% extends 'adminapp/base.html' %}
{% block content %}
{% if user.image %}
     <img src="{{ user.image.url }}"
{% endif %}

    <form class="pure-form" enctype='multipart/form-data' action="{% url 'admin:upgrade_user' user.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button pure-button-primary" type="submit" value="Сохранить">
    </form>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<a href="{% url 'admin:create_user' %}" class="pure-button pure-button-primary">Создать пользователя</a>
<div class="users_list">
    {% for user in object_list %}
    <div class="basket_record">
        <span>{{ user.username }}</span>
        <span>{{ user.city }}</span>
        {% if user.image %}
        <img class="user-image" src="{{ user.image.url }}" alt="{{ user.username }}">
        {% endif %}
        <a href="{% url 'admin:update_user' user.pk %}" class="pure-button pure-button-primary">Редактировать</a>
        <a href="{% url 'admin:delete_user' user.pk %}" class="pure-button pure-button-primary">Удалить</a>
    </div>
    {% endfor %}
</div>
{% endblock %}