geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
    path("", basketapp.view, name="view"),
    path("add/<int:product_id>/", basketapp.add, name="add"),
    path("remove/<int:basket_id>/", basketapp.remove, name="remove"),
    path("edit/<int:basket_id>/<int:quantity>/", basketapp.edit, name="edit"),

]

geekshop/geekshop/urls.py
from mainapp import views as mainapp
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.main, name="index"),
    path("products/", mainapp.products, name="products"),
    path("contact/", mainapp.contact, name="contact"),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("category/<int:pk>/", mainapp.category, name="category"),
    path("product/<int:pk>/", mainapp.product, name="product"),
    path("products/<int:pk>/", mainapp.category, name="category"),
    path("products/<int:pk>/<int:page>/", mainapp.category, name="category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geekshop/mainapp/models.py
from distutils.command.upload import upload
from email.mime import image
from unicodedata import name
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.CharField(max_length=140)
    is_active = models.BooleanField(default=True)


def __str__(self):
    return f'{self.id}: {self.name}'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=25)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product_images', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quatity = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)


def __str__(self):
    return f'{self.id}: {self.name}'

geekshop/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
import json
from .models import Product, Category


with open('data.txt') as json_file:
    product_list = json.load(json_file)

MENU_LINKS = {
    "index": "Главная",
    "products": "Продукты",
    "contact": "Контакты",
}


def main(request):
    return render(request, "mainapp/index.html", context={
        "title": "Главная",
        "menu": MENU_LINKS,
    })


def products(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)[:3]
    return render(request, "mainapp/products.html", context={
        "title": "Продукты",
        "menu": MENU_LINKS,
        "hot_product": hot_product,
        "products": products,
        "categories": categories,
    })

def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category).order_by('price')
    paginator = Paginator(products, per_page=3)
    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse('category', args=[category.id]))
    return render(
        request, 
        "mainapp/category.html", 
        context={
            "title": 'Продукты',
            "menu": MENU_LINKS,
            "products": paginator.page(page),
            "category": category,
            "categories": categories,
        }
    )
    


def contact(request):
    return render(request, "mainapp/contact.html", context={
        "title": "Контакты",
        "menu": MENU_LINKS,
    })

def product(request, pk):
    categories = Category.objects.all()
    product = get_object_or_404(Product, pk=pk)
    return render(request, "mainapp/product.html", context={
        "title": product.name,
        "menu": MENU_LINKS,
        "product": product,
        "category": product.category,
        "categories": categories,
    })

geekshop/mainapp/templates/mainapp/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/pure-min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
        <div class="clr"></div>
    </div>
    
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB </p>
        <div class="social">
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
    
</body>
</html>

geekshop/mainapp/templates/mainapp/category.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="hero-white">
	{% include 'mainapp/includes/main_menu_inc.html' %}
    
</div>

<div class="details">
	<div class="links clearfix">
		{% include 'mainapp/includes/categories_menu_inc.html' %}
    </div>
	
	<div class="category-products related">
		<div class="title clearfix">
			<h2>{{ category.name }}</h2>
			<span class="explore">
				{% if products.has_next %}
				<a href="{% url 'category' category.id  products.next_page_number %}">Следующая страница</a>
				{% endif %}
				{% if products.has_previous %}			
				<a href="{% url 'category' category.id  products.previous_page_number %}">Предыдущая страница</a>
				{% endif %}
			</span>
		</div>
		<div class="related-products clearfix">
			{% include 'mainapp\includes\product_list_inc.html' %}
		</div>
	</div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="hero">
	{% include 'mainapp/includes/main_menu_inc.html' %}
	<h1>наши контакты</h1>
</div>

<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="slider">
	{% include 'mainapp/includes/main_menu_inc.html' %}
	
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
	</div>	
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>

<div class="featured">
	<div class="featured-menu">
		<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		<div class="block">
			<a href="#"><img src="/static/img/product-1.jpg" alt=""> 
				<div class="text">
					<img src="/static/img/icon-hover.png" alt="img">
					<h4>Отличный стул</h4>
					<p>Расположитесь комфортно. </p>
				</div> 
			</a>
		</div>
		<div class="block">
			<a href="#"><img src="/static/img/product-2.jpg" alt="">
				<div class="text">
					<img src="/static/img/icon-hover.png" alt="">
					<h4>Стул повышенного качества</h4>
					<p>Не оторваться. </p>
				</div>
			</a>
		</div>	
	</div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="hero-white">
	{% include 'mainapp/includes/main_menu_inc.html' %}
</div>

<div class="details">
	<div class="links clearfix">
		{% include 'mainapp/includes/categories_menu_inc.html' %}
	</div>
	
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ product.image.url }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{{ product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>
		
		<div class="description">
			<h3 class="big-bold">{{ product.name }}</h3>
			<p class="price"> {{ product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' product.pk %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text"> {{ product.description | linebreaks }}</div>
		</div>
	</div>
	
	
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="hero-white">
	{% include 'mainapp/includes/main_menu_inc.html' %}
</div>

<div class="details">
	<div class="links clearfix">
		{% include 'mainapp/includes/categories_menu_inc.html' %}
	</div>
	
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ hot_product.image.url }}">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="{{ hot_product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ hot_product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{{ hot_product.image.url }}" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>
		
		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">Горячее предложение</h3>
			<p class="price"> {{ hot_product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text"> {{ hot_product.description | linebreaks }}</div>
		</div>
	</div>
	
	<div class="related">
		<div class="title clearfix">
			<h2>Еще продукты</h2>
			<a class="explore" href="#">показать все <img src="/static/css/img/arrow.png" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% include 'mainapp\includes\product_list_inc.html' %}
		</div>
	</div>
</div>
{% endblock %}